import { Chord } from '../models/chord.model';

export const DEFAULT_CHORDS: Chord[] = [
  {
    id: 'chord-do-mayor',
    name: 'Do+',
    rootNote: 'DO',
    positions: [
      { stringNumber: 1, fret: 0 },
      { stringNumber: 2, fret: 1 },
      { stringNumber: 3, fret: 0 },
      { stringNumber: 4, fret: 2 },
      { stringNumber: 5, fret: 3 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-do-menor',
    name: 'Do-',
    rootNote: 'DO',
    positions: [
      { stringNumber: 1, fret: 3 },
      { stringNumber: 2, fret: 4 },
      { stringNumber: 3, fret: 5 },
      { stringNumber: 4, fret: 5 },
      { stringNumber: 5, fret: 3 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-do7',
    name: 'Do7',
    rootNote: 'DO',
    positions: [
      { stringNumber: 1, fret: 0 },
      { stringNumber: 2, fret: 1 },
      { stringNumber: 3, fret: 3 },
      { stringNumber: 4, fret: 2 },
      { stringNumber: 5, fret: 3 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-re-mayor',
    name: 'Re+',
    rootNote: 'RE',
    positions: [
      { stringNumber: 1, fret: 2 },
      { stringNumber: 2, fret: 3 },
      { stringNumber: 3, fret: 2 },
      { stringNumber: 4, fret: 0 },
      { stringNumber: 5, fret: 'X' },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-re-menor',
    name: 'Re-',
    rootNote: 'RE',
    positions: [
      { stringNumber: 1, fret: 1 },
      { stringNumber: 2, fret: 3 },
      { stringNumber: 3, fret: 2 },
      { stringNumber: 4, fret: 0 },
      { stringNumber: 5, fret: 'X' },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-re7',
    name: 'Re7',
    rootNote: 'RE',
    positions: [
      { stringNumber: 1, fret: 2 },
      { stringNumber: 2, fret: 1 },
      { stringNumber: 3, fret: 2 },
      { stringNumber: 4, fret: 0 },
      { stringNumber: 5, fret: 'X' },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-mi-mayor',
    name: 'Mi+',
    rootNote: 'MI',
    positions: [
      { stringNumber: 1, fret: 0 },
      { stringNumber: 2, fret: 0 },
      { stringNumber: 3, fret: 1 },
      { stringNumber: 4, fret: 2 },
      { stringNumber: 5, fret: 2 },
      { stringNumber: 6, fret: 0 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-mi-menor',
    name: 'Mi-',
    rootNote: 'MI',
    positions: [
      { stringNumber: 1, fret: 0 },
      { stringNumber: 2, fret: 0 },
      { stringNumber: 3, fret: 0 },
      { stringNumber: 4, fret: 2 },
      { stringNumber: 5, fret: 2 },
      { stringNumber: 6, fret: 0 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-mi7',
    name: 'Mi7',
    rootNote: 'MI',
    positions: [
      { stringNumber: 1, fret: 0 },
      { stringNumber: 2, fret: 0 },
      { stringNumber: 3, fret: 1 },
      { stringNumber: 4, fret: 0 },
      { stringNumber: 5, fret: 2 },
      { stringNumber: 6, fret: 0 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-fa-mayor',
    name: 'Fa+',
    rootNote: 'FA',
    positions: [
      { stringNumber: 1, fret: 1 },
      { stringNumber: 2, fret: 1 },
      { stringNumber: 3, fret: 2 },
      { stringNumber: 4, fret: 3 },
      { stringNumber: 5, fret: 3 },
      { stringNumber: 6, fret: 1 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-fa-menor',
    name: 'Fa-',
    rootNote: 'FA',
    positions: [
      { stringNumber: 1, fret: 1 },
      { stringNumber: 2, fret: 1 },
      { stringNumber: 3, fret: 1 },
      { stringNumber: 4, fret: 3 },
      { stringNumber: 5, fret: 3 },
      { stringNumber: 6, fret: 1 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-fa7',
    name: 'Fa7',
    rootNote: 'FA',
    positions: [
      { stringNumber: 1, fret: 1 },
      { stringNumber: 2, fret: 1 },
      { stringNumber: 3, fret: 2 },
      { stringNumber: 4, fret: 1 },
      { stringNumber: 5, fret: 3 },
      { stringNumber: 6, fret: 1 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-sol-mayor',
    name: 'Sol+',
    rootNote: 'SOL',
    positions: [
      { stringNumber: 1, fret: 3 },
      { stringNumber: 2, fret: 0 },
      { stringNumber: 3, fret: 0 },
      { stringNumber: 4, fret: 0 },
      { stringNumber: 5, fret: 2 },
      { stringNumber: 6, fret: 3 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-sol-menor',
    name: 'Sol-',
    rootNote: 'SOL',
    positions: [
      { stringNumber: 1, fret: 3 },
      { stringNumber: 2, fret: 3 },
      { stringNumber: 3, fret: 3 },
      { stringNumber: 4, fret: 5 },
      { stringNumber: 5, fret: 5 },
      { stringNumber: 6, fret: 3 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-sol7',
    name: 'Sol7',
    rootNote: 'SOL',
    positions: [
      { stringNumber: 1, fret: 1 },
      { stringNumber: 2, fret: 0 },
      { stringNumber: 3, fret: 0 },
      { stringNumber: 4, fret: 0 },
      { stringNumber: 5, fret: 2 },
      { stringNumber: 6, fret: 3 },
    ],
    isCustom: false,
  },
  {
    id: 'chord-la-mayor',
    name: 'La+',
    rootNote: 'LA',
    positions: [
      { stringNumber: 1, fret: 0 },
      { stringNumber: 2, fret: 2 },
      { stringNumber: 3, fret: 2 },
      { stringNumber: 4, fret: 2 },
      { stringNumber: 5, fret: 0 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-la-menor',
    name: 'La-',
    rootNote: 'LA',
    positions: [
      { stringNumber: 1, fret: 0 },
      { stringNumber: 2, fret: 1 },
      { stringNumber: 3, fret: 2 },
      { stringNumber: 4, fret: 2 },
      { stringNumber: 5, fret: 0 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-la7',
    name: 'La7',
    rootNote: 'LA',
    positions: [
      { stringNumber: 1, fret: 0 },
      { stringNumber: 2, fret: 2 },
      { stringNumber: 3, fret: 0 },
      { stringNumber: 4, fret: 2 },
      { stringNumber: 5, fret: 0 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-si-mayor',
    name: 'Si+',
    rootNote: 'SI',
    positions: [
      { stringNumber: 1, fret: 2 },
      { stringNumber: 2, fret: 4 },
      { stringNumber: 3, fret: 4 },
      { stringNumber: 4, fret: 4 },
      { stringNumber: 5, fret: 2 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-si-menor',
    name: 'Si-',
    rootNote: 'SI',
    positions: [
      { stringNumber: 1, fret: 2 },
      { stringNumber: 2, fret: 3 },
      { stringNumber: 3, fret: 4 },
      { stringNumber: 4, fret: 4 },
      { stringNumber: 5, fret: 2 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
  {
    id: 'chord-si7',
    name: 'Si7',
    rootNote: 'SI',
    positions: [
      { stringNumber: 1, fret: 2 },
      { stringNumber: 2, fret: 0 },
      { stringNumber: 3, fret: 2 },
      { stringNumber: 4, fret: 1 },
      { stringNumber: 5, fret: 2 },
      { stringNumber: 6, fret: 'X' },
    ],
    isCustom: false,
  },
];